<?php

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 51,
                'model_type' => 'App\\Color',
                'model_id' => 7,
                'collection_name' => 'swatch',
                'name' => 'vc-sandbar-sandbar',
                'file_name' => 'vc-sandbar-sandbar.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 15829,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 51,
                'created_at' => '2020-01-29 13:08:38',
                'updated_at' => '2020-01-29 13:08:38',
            ),
            1 => 
            array (
                'id' => 52,
                'model_type' => 'App\\Color',
                'model_id' => 8,
                'collection_name' => 'swatch',
                'name' => 'vc-dune-white',
                'file_name' => 'vc-dune-white.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 6100,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 52,
                'created_at' => '2020-01-29 13:08:39',
                'updated_at' => '2020-01-29 13:08:39',
            ),
            2 => 
            array (
                'id' => 53,
                'model_type' => 'App\\Color',
                'model_id' => 9,
                'collection_name' => 'swatch',
                'name' => 'vc-dune-biscuit',
                'file_name' => 'vc-dune-biscuit.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 6194,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 53,
                'created_at' => '2020-01-29 13:08:40',
                'updated_at' => '2020-01-29 13:08:40',
            ),
            3 => 
            array (
                'id' => 54,
                'model_type' => 'App\\Color',
                'model_id' => 10,
                'collection_name' => 'swatch',
                'name' => 'vc-sandbar-white',
                'file_name' => 'vc-sandbar-white.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 15682,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 54,
                'created_at' => '2020-01-29 13:08:41',
                'updated_at' => '2020-01-29 13:08:41',
            ),
            4 => 
            array (
                'id' => 55,
                'model_type' => 'App\\Color',
                'model_id' => 11,
                'collection_name' => 'swatch',
                'name' => 'vc-sandbar-biscuit',
                'file_name' => 'vc-sandbar-biscuit.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 15666,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 55,
                'created_at' => '2020-01-29 13:08:42',
                'updated_at' => '2020-01-29 13:08:42',
            ),
            5 => 
            array (
                'id' => 64,
                'model_type' => 'App\\Color',
                'model_id' => 3,
                'collection_name' => 'swatch',
                'name' => 'veincut-dune',
                'file_name' => 'veincut-dune.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 8508,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 64,
                'created_at' => '2020-01-29 13:08:59',
                'updated_at' => '2020-01-29 13:08:59',
            ),
            6 => 
            array (
                'id' => 65,
                'model_type' => 'App\\Color',
                'model_id' => 4,
                'collection_name' => 'swatch',
                'name' => 'veincut-sandbar',
                'file_name' => 'veincut-sandbar.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 57290,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 65,
                'created_at' => '2020-01-29 13:09:01',
                'updated_at' => '2020-01-29 13:09:01',
            ),
            7 => 
            array (
                'id' => 66,
                'model_type' => 'App\\Color',
                'model_id' => 5,
                'collection_name' => 'swatch',
                'name' => 'crosscut-dune',
                'file_name' => 'crosscut-dune.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 21203,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 66,
                'created_at' => '2020-01-29 13:09:05',
                'updated_at' => '2020-01-29 13:09:05',
            ),
            8 => 
            array (
                'id' => 67,
                'model_type' => 'App\\Color',
                'model_id' => 6,
                'collection_name' => 'swatch',
                'name' => 'white-brick-tile',
                'file_name' => 'white-brick-tile.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 9086,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 67,
                'created_at' => '2020-01-29 13:09:06',
                'updated_at' => '2020-01-29 13:09:06',
            ),
            9 => 
            array (
                'id' => 90,
                'model_type' => 'App\\Color',
                'model_id' => 14,
                'collection_name' => 'swatch',
                'name' => 'bright-polished-silver',
                'file_name' => 'bright-polished-silver.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 3995,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 90,
                'created_at' => '2020-01-29 13:09:44',
                'updated_at' => '2020-01-29 13:09:44',
            ),
            10 => 
            array (
                'id' => 113,
                'model_type' => 'App\\Color',
                'model_id' => 16,
                'collection_name' => 'swatch',
                'name' => 'teak',
                'file_name' => 'teak.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 5917,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 113,
                'created_at' => '2020-01-29 13:10:33',
                'updated_at' => '2020-01-29 13:10:33',
            ),
            11 => 
            array (
                'id' => 126,
                'model_type' => 'App\\Color',
                'model_id' => 12,
                'collection_name' => 'swatch',
                'name' => 'sandbar',
                'file_name' => 'sandbar.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 6678,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 126,
                'created_at' => '2020-01-29 13:10:58',
                'updated_at' => '2020-01-29 13:10:58',
            ),
            12 => 
            array (
                'id' => 127,
                'model_type' => 'App\\Color',
                'model_id' => 13,
                'collection_name' => 'swatch',
                'name' => 'dune',
                'file_name' => 'dune.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 5336,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 127,
                'created_at' => '2020-01-29 13:11:00',
                'updated_at' => '2020-01-29 13:11:00',
            ),
            13 => 
            array (
                'id' => 270,
                'model_type' => 'App\\Color',
                'model_id' => 1,
                'collection_name' => 'swatch',
                'name' => 'white',
                'file_name' => 'white.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 1856,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 270,
                'created_at' => '2020-01-29 13:15:34',
                'updated_at' => '2020-01-29 13:15:34',
            ),
            14 => 
            array (
                'id' => 271,
                'model_type' => 'App\\Color',
                'model_id' => 2,
                'collection_name' => 'swatch',
                'name' => 'biscuit',
                'file_name' => 'biscuit.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 1786,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 271,
                'created_at' => '2020-01-29 13:15:37',
                'updated_at' => '2020-01-29 13:15:37',
            ),
            15 => 
            array (
                'id' => 277,
                'model_type' => 'App\\Color',
                'model_id' => 19,
                'collection_name' => 'swatch',
                'name' => 'frosted',
                'file_name' => 'frosted.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 4320,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 277,
                'created_at' => '2020-01-29 13:15:49',
                'updated_at' => '2020-01-29 13:15:49',
            ),
            16 => 
            array (
                'id' => 283,
                'model_type' => 'App\\Color',
                'model_id' => 18,
                'collection_name' => 'swatch',
                'name' => 'clear',
                'file_name' => 'clear.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 2350,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 283,
                'created_at' => '2020-01-29 13:16:00',
                'updated_at' => '2020-01-29 13:16:00',
            ),
            17 => 
            array (
                'id' => 286,
                'model_type' => 'App\\Color',
                'model_id' => 17,
                'collection_name' => 'swatch',
                'name' => 'polished-chrome',
                'file_name' => 'polished-chrome.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 3995,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 286,
                'created_at' => '2020-01-29 13:16:06',
                'updated_at' => '2020-01-29 13:16:06',
            ),
            18 => 
            array (
                'id' => 287,
                'model_type' => 'App\\Color',
                'model_id' => 15,
                'collection_name' => 'swatch',
                'name' => 'brushed-nickel',
                'file_name' => 'brushed-nickel.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'size' => 22332,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'responsive_images' => '[]',
                'order_column' => 287,
                'created_at' => '2020-01-29 13:16:07',
                'updated_at' => '2020-01-29 13:16:07',
            ),
        ));
        
        
    }
}