module.exports = {
    prefix: '',
    important: false,
    separator: ':',
    theme: {
        extend: {
            colors: {
                transparent: 'transparent',
                'black-#000': '#000000',
                'white-#fff': '#ffffff',
                'gray-fafafa': '#fafafa',
                'gray-ebebeb': '#ebebeb',
                'gray-333': '#333',
                'gray-999': '#999',
                'gray-ddd': '#ddd',
                'gray-aaa': '#aaa',
                'gray-bbb': '#bbb',
                'gray-555': '#555',
                'gray-666': '#666',
                'gray-111': '#111',
                'gray-f2f2f2': '#f2f2f2',
                'gray-e5e5e5': '#e5e5e5',
                'gray-cdced0': '#cdced0',
                'gray-dcdcdc': '#dcdcdc',
                'gray-e0e0e0': '#e0e0e0',
                'gray-ededed': '#ededed',
                'orange-ff9600': '#ff9600',
                'red-f8d7da': '#f8d7da',
                'red-ce1400': '#ce1400',
                'red-d91a1a': '#d91a1a',

                'red-870e14': '#870e14',
                'red-c70c16': '#c70c16',
                'red-f6d7da': '#f6d7da',

                'green-094d16': '#094d16',
                'green-0cc72e': '#0cc72e',
                'green-d5f5da': '#d5f5da',

                'green-45db5e': '#45db5e',
                'green-074854': '#074854',
                'green-4e8892': '#4e8892',
                'blue-00849c': '#00849c',
                'blue-85c6e4': '#85c6e4',
                'blue-0076fe': '#0076fe',
                'blue-e5f2f5': '#e5f2f5',
                'blue-8e9c9e': '#8e9c9e',
                'blue-0c839b': '#0c839b',
                'blue-055565': '#055565',
            },
        },
        spacing: {
            px: '1px',
            '0': '0',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '8': '2rem',
            '10': '2.5rem',
            '12': '3rem',
            '14': '3.5rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '28': '7rem',
            '32': '8rem',
            '36': '9rem',
            '40': '10rem',
            '44': '11rem',
            '48': '12rem',
            '52': '13rem',
            '56': '14rem',
            '60': '15rem',
        },
        screens: {
            // sm: '576px',
            md: '768px',
            lg: '1024px',
        },
        fontFamily: {
            sans: [
                'NunitoSans',
                '-apple-system',
                '"Segoe UI"',
                'Roboto',
                'Arial',
            ],
            serif: [
                'Georgia',
                'Cambria',
                '"Times New Roman"',
                'serif',
            ],
        },
        fontSize: {
            '1': '1rem',
            '11': '1.1rem',
            '12': '1.2rem',
            '13': '1.3rem',
            '14': '1.4rem',
            '15': '1.5rem',
            '16': '1.6rem',
            '17': '1.7rem',
            '18': '1.8rem',
            '19': '1.9rem',
            '20': '2rem',
            '21': '2.1rem',
            '22': '2.2rem',
            '23': '2.3rem',
            '24': '2.4rem',
            '25': '2.5rem',
            '26': '2.6rem',
            '27': '2.7rem',
            '28': '2.8rem',
            '29': '2.9rem',
            '30': '3rem',
            '32': '3.2rem',
            '34': '3.4rem',
            '36': '3.6rem',
            '40': '4rem',
            '42': '4.2rem',
            '50': '5rem',
            '54': '5.4rem',
            '60': '6rem',
            '64': '6.4rem',
            '72': '7.2rem',
            '80': '8rem',
            '90': '9rem',
        },
        fontWeight: {
            normal: '400',
            light: '300',
            bold: '700',
            extrabold: '800',
        },
        lineHeight: {
            none: '1',
            tight: '1.25',
            snug: '1.375',
            normal: '1.5',
            relaxed: '1.625',
            loose: '2',
        },
        letterSpacing: {
            tighter: '-0.05em',
            tight: '-0.025em',
            normal: '0',
            wide: '0.025em',
            wider: '0.05em',
            widest: '0.1em',
        },
        textColor: theme => theme('colors'),
        backgroundColor: theme => theme('colors'),
        backgroundPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
        },
        backgroundSize: {
            auto: 'auto',
            cover: 'cover',
            contain: 'contain',
        },
        borderWidth: {
            default: '1px',
            '0': '0',
            '2': '2px',
            '3': '3px',
            '8': '8px',
        },
        borderColor: theme => ({
            ...theme('colors'),
            default: theme('colors.gray.300', 'currentColor'),
        }),
        borderRadius: {
            none: '0',
            lg: '0.5rem',
            '10': '1rem',
            '20': '2rem',
            full: '9999px',
        },
        cursor: {
            auto: 'auto',
            default: 'default',
            pointer: 'pointer',
            text: 'text',
        },
        width: theme => ({
            auto: 'auto',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '8': '2rem',
            '10': '2.5rem',
            '12': '3rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '32': '8rem',
            '44': '10rem',
            '64': '16rem',
            '80': '20rem',
            '1/2': '50%',
            'flex1/2': '49%',
            '1/3': '33.33333%',
            '2/3': '66.66667%',
            '1/4': '25%',
            'flex1/3': '31.2%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.66667%',
            '5/6': '83.33333%',
            '1/10': '10%',
            full: '100%',
            screen: '100vw',
        }),
        height: theme => ({
            auto: 'auto',
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
        }),
        minWidth: {
            '0': '0',
            full: '100%',
        },
        minHeight: {
            '0': '0',
            full: '100%',
            screen: '100vh',
        },
        maxWidth: {
            xs: '20rem',
            sm: '24rem',
            md: '28rem',
            lg: '32rem',
            xl: '36rem',
            page: '124rem',
            pagew: '150rem',
            '2xl': '42rem',
            '3xl': '48rem',
            '4xl': '56rem',
            '5xl': '69rem',
            '80': '80rem',
            full: '100%',
        },
        maxHeight: {
            full: '100%',
            screen: '100vh',
        },
        padding: theme => theme('spacing'),
        margin: (theme, {negative}) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
        }),
        zIndex: {
            auto: 'auto',
            '0': '0',
            '10': '10',
            '20': '20',
            '30': '30',
            '40': '40',
            '50': '50',
        },
        opacity: {
            '0': '0',
            '25': '0.25',
            '50': '0.5',
            '75': '0.75',
            '100': '1',
        },
        flex: {
            '1': '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
        },
        flexGrow: {
            '0': '0',
            default: '1',
        },
        flexShrink: {
            '0': '0',
            default: '1',
        },
        order: {
            first: '-9999',
            last: '9999',
            none: '0',
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
        },
        listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
        },
        inset: {
            '0': '0',
            auto: 'auto',
        },
        container: {},
    },
    variants: {
        appearance: false,
        backgroundAttachment: ['responsive'],
        backgroundColor: ['responsive', 'hover'],
        backgroundPosition: ['responsive'],
        backgroundRepeat: ['responsive'],
        backgroundSize: ['responsive'],
        borderCollapse: false,
        borderColor: ['responsive', 'hover'],
        borderRadius: ['responsive'],
        borderStyle: ['responsive'],
        borderWidth: ['responsive'],
        cursor: ['responsive'],
        display: ['responsive'],
        flexDirection: ['responsive'],
        flexWrap: ['responsive'],
        alignItems: ['responsive'],
        alignSelf: ['responsive'],
        justifyContent: ['responsive'],
        alignContent: ['responsive'],
        flex: ['responsive'],
        flexGrow: ['responsive'],
        flexShrink: false,
        order: ['responsive'],
        float: ['responsive'],
        fontFamily: ['responsive'],
        fontWeight: ['responsive', 'hover'],
        height: ['responsive'],
        lineHeight: ['responsive'],
        listStylePosition: false,
        listStyleType: false,
        margin: ['responsive'],
        maxHeight: ['responsive'],
        maxWidth: ['responsive'],
        minHeight: ['responsive'],
        minWidth: ['responsive'],
        objectFit: false,
        objectPosition: false,
        opacity: ['responsive'],
        outline: false,
        overflow: ['responsive'],
        padding: ['responsive'],
        pointerEvents: false,
        position: ['responsive'],
        inset: false,
        resize: false,
        boxShadow: false,
        fill: false,
        stroke: false,
        tableLayout: false,
        textAlign: ['responsive'],
        textColor: ['responsive', 'hover'],
        fontSize: ['responsive'],
        fontStyle: ['responsive'],
        textTransform: ['responsive'],
        textDecoration: ['responsive', 'hover'],
        fontSmoothing: false,
        letterSpacing: false,
        userSelect: false,
        verticalAlign: ['responsive'],
        visibility: ['responsive'],
        whitespace: ['responsive'],
        wordBreak: false,
        width: ['responsive'],
        zIndex: ['responsive'],
    },
    corePlugins: {},
    plugins: [],
};
