<?php

namespace App\SubModels;

use App\Color;
use App\Interfaces\SubModel;
use App\Product;
use App\ProductCategory;
use App\ProductSubCategory;
use App\Scopes\BathTubScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;

/**
 * App\SubModels\BathTub
 *
 * @property int $id
 * @property string $sku
 * @property float $price
 * @property int $product_category_id
 * @property int|null $product_sub_category_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\ProductCategory $category
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Color[] $colors
 * @property-read int|null $colors_count
 * @property-read mixed $plumbing_position
 * @property-read mixed $size
 * @property-read mixed $tub_color_id
 * @property-read \Illuminate\Database\Eloquent\Collection|\Spatie\MediaLibrary\Models\Media[] $media
 * @property-read int|null $media_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Option[] $options
 * @property-read int|null $options_count
 * @property-read \App\ProductSubCategory|null $subCategory
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub whereProductCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub whereProductSubCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub whereSku($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\SubModels\BathTub whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class BathTub extends Product implements SubModel
{
    protected  $table = 'products';

    protected $appends = ['size', 'plumbing_position', 'tub_color_id'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new BathTubScope);
    }

    public function getSizeAttribute()
    {
        return Cache::rememberForever('tub_size_' . $this->id, function(){
            $width = $this->options()->where('key','width')->first()->value ?? '?';
            $depth = $this->options()->where('key', 'depth')->first()->value ?? '?';
            return $width . 'x' . $depth;
        });
    }

    public function getPlumbingPositionAttribute()
    {
        return Cache::rememberForever('plumbing_position_' . $this->id, function (){
            return $this->options()->where('key', 'plumbing_position')->first()->value ?? '?';
        });
    }

    public function getTubColorIdAttribute()
    {
        return Cache::tags(['colors'])->rememberForever('tub_color_' . $this->id, function (){
            return $this->options()->where('key', 'tub_color_id')->first()->value ?? '?';
        });
    }


    public static function getResponseData(Collection $products)
    {
        $sizes = $products->pluck('size')->unique()->values();
        $drains = BathTubDrain::all()->toArray();
        $tubColorIds = $products->pluck('tub_color_id')->unique()->toArray();
        $tubColors = Color::findMany($tubColorIds, ['id', 'name'])->toArray();
        $plumbingPositions = $products->pluck('plumbing_position')->unique()->toArray();
        $subCategories = ProductSubCategory::select('id', 'name')
            ->withCount('products')
            ->where('product_category_id', ProductCategory::BATHTUBS)
            ->get()->each->getImage()->toArray();

        return [
            'products' => $products,
            'sizes' => $sizes,
            'tub_colors' => $tubColors,
            'plumbing_positions' => $plumbingPositions,
            'drains' => $drains,
            'subCategories' => $subCategories,
        ];
    }
}
