<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * @see \App\Http\Controllers\AdminDashboardController
 */
class AdminDashboardControllerTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed('RoleAndPermissionSeeder');
        $this->user = factory(\App\User::class)->state('admin')->create();
    }

    /**
     * @test
     */
    public function charts_returns_an_ok_response()
    {
        $response = $this->actingAs($this->user)->get(route('admin.dashboard.charts'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $user = factory(\App\User::class)->state('admin')->create();

        $response = $this->actingAs($this->user)->get(route('dashboard.admin'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
