<?php

namespace Tests\Feature\Http\Controllers;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class HomeControllerTest extends TestCase
{
    use RefreshDatabase;

    protected $route;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
        $this->seed('RoleAndPermissionSeeder');
        $this->route = route('home');
    }

    /** @test */
    public function it_redirects_an_admin_user_to_the_admin_dashboard()
    {
        $user = factory(User::class)->state('admin')->create();
        $response = $this->actingAs($user)->get($this->route);
        $response->assertRedirect(route('dashboard.admin'));
    }

    /** @test */
    public function it_redirects_a_sales_rep_to_the_sales_dashboard()
    {
        $user = factory(User::class)->state('salesRep')->create();
        $response = $this->actingAs($user)->get($this->route);
        $response->assertRedirect(route('dashboard.mine'));
    }
}
