<?php

namespace Tests\Unit\Tools;

use App\User;
use Tests\TestCase;
use Illuminate\Support\Facades\File;
use Spatie\MediaLibrary\Models\Media;
use Illuminate\Support\Facades\Storage;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserAvatar extends TestCase
{
    use RefreshDatabase;

    protected $path;

    /** @test */
    public function it_saves_a_remote_url_as_local_media()
    {
        $user = factory(User::class)->create();
        $avatarUpdater = new \App\Tools\UserAvatar;
        $media = $avatarUpdater->update($user, 'https://www.gravatar.com/avatar/'.md5($user->email));
        $this->assertInstanceOf(Media::class, $media);
        $this->assertEquals(1, $user->media()->count());
        $this->assertFileExists($media->getPath());

        $this->path = $media->getPath();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unlink($this->path);
    }
}
