<?php

namespace App\Providers;

use App\Listeners\RunIdeHelperModels;
use Illuminate\Database\Events\MigrationsEnded;
use Illuminate\Support\Facades\Event;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [

    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();


    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        if(app()->environment('local')){
            $this->listen = [ MigrationsEnded::class => [
                RunIdeHelperModels::class,
            ]];
        }
    }
}
