name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, imagick
          tools: pecl
          coverage: none

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.dusk.ci', '.env');"

      - name: Setup Composer Nova Auth
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run dev

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          TELESCOPE_ENABLED: false

      - name: Deploy to staging
        uses: bredmor/vapor-action@master
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          MIX_PUSHER_APP_KEY:  ${{ secrets.MIX_PUSHER_APP_KEY }}
          MIX_FLARE_JS_KEY:  ${{ secrets.MIX_FLARE_JS_KEY }}
        with:
          args: deploy staging
